# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# IFrame Panels on Sidebar
panel_iframe:
  pihole:
    title: Pi-Hole
    icon: mdi:dns
    url: http://172.17.0.1:8081/admin/
    require_admin: true
  portainer:
    title: Portainer
    icon: mdi:docker
    url: https://172.17.0.1:9443/
    require_admin: true
  zigbee2mqtt:
    title: Zigbee2MQTT
    icon: mdi:zigbee
    url: http://172.17.0.1:8080/
    require_admin: true
  nodered:
    title: Node-RED
    icon: mdi:lan
    url: http://172.17.0.1:1880/
    require_admin: true
  uptimekuma:
    title: Uptime Kuma
    icon: mdi:antenna
    url: http://172.17.0.1:3001/
    require_admin: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml